### ISSUE TITLE
after hook for .build

### ISSUE THREAD

**Issue by sungwoncho** [percolatestudio/meteor-factory#10]
How about making after hook run for `Factory.build()`? Currently it only runs for `Factory.create()`.

A useful case would be when simulating a document not yet inserted to the db.

```javascript
// post object not persisted yet
Factory.define('newPost', Posts, {
  body: 'testBody',
}).after(function (post) {
  delete post._id;
});
```

**Comment by dburles** [comment]
Hey @sungwoncho not sure it makes sense, can you elaborate on your use-case?

**Comment by sungwoncho** [comment]
Currently `Factory.build()` returns an object with a random `_id`. But sometimes I would like to generate an object without `_id`.

Here is an example:

```javascript
it("creates a post", function(){
  var post = Factory.build('post');

  Meteor.call('submitPost', post);

  expect(Posts.find().count()).to.equal(1);
});
```

If I have a `check` inside the method `submitPost`, the test will fail because `post` already has `_id` and Meteor will complain about it.

    Error: Match error: Unknown key in field _id

So in the use case, I was trying to get rid of `_id` using after hook. Does it make sense?

**Comment by dburles** [comment]
Hmm, why not just do something like `var post = _.omit(Factory.build('post'), '_id');`? Not requiring the `_id` field is pretty specific to that test case so it makes sense to me to be removing it there rather than within a hook.

**Comment by sungwoncho** [comment]
Thanks. I will go down that road.

On a related note, wouldn't it make more sense if `Factory.build()` did not stub `_id` with a random value? In my eyes, `Factory.build()` is simply building a document, not persisting it; and `_id` value in the returned object is confusing.

**Comment by dburles** [comment]
My memory is hazy but I think there was a reason we went with that originally. Maybe something to do with it appearing the same as a document would had it been retrieved from the database. I'll comment back if I recall any more detail on that :) - @tmeasday ?

**Comment by tmeasday** [comment]
I'm not sure. Potentially for validation somewhere along the line..
