### ISSUE TITLE
Feature request: Hooks before insertion of document

### ISSUE THREAD

**Issue by lentan1029** [percolatestudio/meteor-factory#9]
Sometimes some fields need to be randomised based on other fields within the document. For eg. DateResponded property should contain a timestamp that is later than DateRequested property for each document.

**Comment by dburles** [comment]
While not really documented, you can reference other fields by `this`. See here: https://github.com/percolatestudio/meteor-factory/blob/master/lib/factory_tests.js#L41-L44

**Comment by lentan1029** [comment]
don't think it works for the example case I gave, since the DateResponded field depends on the randomised result of the DateRequested field

**Comment by dburles** [comment]
Hey @lentan1029 you can do something like:
```
  DateRequested: function() {
    return new Date();
  },
  DateResponded: function() {
    return moment(this.DateRequested).add(1, 'days').toDate();
  }
```
